version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Cars/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=;User=sa;Password=abcDEF123#;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "abcDEF123#"
      ACCEPT_EULA: "Y"
